name = "short"
account_id = "41f6f507a22c7eec431dbc5e9670c73d"
workers_dev = true
main = "index.js"
compatibility_date = "2022-04-05"

kv_namespaces = [
    { binding = "URL_SPACE", id = "f9aaaeab12df4665869384f33b1e2d51" }
]






