name = "dalle"
main = "src/index.js"
compatibility_date = "2023-03-21"

kv_namespaces = [
    { binding = "MY_KV", id = "0fa41388238d45819a302d18ecdb3d5b" }
]

[[r2_buckets]]
binding = 'MY_BUCKET' 
bucket_name = 'bucket1'

